version: '3'

services:
  hello-world-app:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: always
    ports:
     - 80:80

  mysql:
    build:
      context: .
      dockerfile: ./Dockerfile.mysql
    restart: always
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=UUii88Bbxx
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local